services:
  - type: web
    name: discord-music-bot
    env: python            # Poetry 모드 끄기
    plan: free
    region: oregon
    buildCommand: |
      # 1) 시스템 패키지로 Opus 코덱과 ffmpeg 설치
      apt-get update && apt-get install -y libopus0 ffmpeg
      # 2) pip 최신화 & 의존성 설치
      pip install -U pip && pip install -r requirements.txt
    startCommand: |
      python bot_local.py
